// AUTO-GENERATED by scripts/generate-season-registry.ts — do not edit.
// Regenerate with: npm run generate-registry
//
// Metro needs static require() calls to bundle the season JSON. The
// requires live inside a function body so each season is parsed lazily
// on first use (inline requires) — only the season being played is ever
// loaded into memory.
import type { GameData } from './gameLoader';

export function loadSeasonFile(file: string): GameData[] | null {
  try {
    switch (file) {
      case 'season-1984.json': return require('./seasons/season-1984.json') as GameData[];
      case 'season-1985.json': return require('./seasons/season-1985.json') as GameData[];
      case 'season-1986.json': return require('./seasons/season-1986.json') as GameData[];
      case 'season-1987.json': return require('./seasons/season-1987.json') as GameData[];
      case 'season-1988.json': return require('./seasons/season-1988.json') as GameData[];
      case 'season-1989.json': return require('./seasons/season-1989.json') as GameData[];
      case 'season-1990.json': return require('./seasons/season-1990.json') as GameData[];
      case 'season-1991.json': return require('./seasons/season-1991.json') as GameData[];
      case 'season-1992.json': return require('./seasons/season-1992.json') as GameData[];
      case 'season-1993.json': return require('./seasons/season-1993.json') as GameData[];
      case 'season-1994.json': return require('./seasons/season-1994.json') as GameData[];
      case 'season-1995.json': return require('./seasons/season-1995.json') as GameData[];
      case 'season-1996.json': return require('./seasons/season-1996.json') as GameData[];
      case 'season-1997.json': return require('./seasons/season-1997.json') as GameData[];
      case 'season-1998.json': return require('./seasons/season-1998.json') as GameData[];
      case 'season-1999.json': return require('./seasons/season-1999.json') as GameData[];
      case 'season-2000.json': return require('./seasons/season-2000.json') as GameData[];
      case 'season-2001.json': return require('./seasons/season-2001.json') as GameData[];
      case 'season-2002.json': return require('./seasons/season-2002.json') as GameData[];
      case 'season-2003.json': return require('./seasons/season-2003.json') as GameData[];
      case 'season-2004.json': return require('./seasons/season-2004.json') as GameData[];
      case 'season-2005.json': return require('./seasons/season-2005.json') as GameData[];
      case 'season-2006.json': return require('./seasons/season-2006.json') as GameData[];
      case 'season-2007.json': return require('./seasons/season-2007.json') as GameData[];
      case 'season-2008.json': return require('./seasons/season-2008.json') as GameData[];
      case 'season-2009.json': return require('./seasons/season-2009.json') as GameData[];
      case 'season-2010.json': return require('./seasons/season-2010.json') as GameData[];
      case 'season-2011.json': return require('./seasons/season-2011.json') as GameData[];
      case 'season-2012.json': return require('./seasons/season-2012.json') as GameData[];
      case 'season-2013.json': return require('./seasons/season-2013.json') as GameData[];
      case 'season-2014.json': return require('./seasons/season-2014.json') as GameData[];
      case 'season-2015.json': return require('./seasons/season-2015.json') as GameData[];
      case 'season-2016.json': return require('./seasons/season-2016.json') as GameData[];
      case 'season-2017.json': return require('./seasons/season-2017.json') as GameData[];
      case 'season-2018.json': return require('./seasons/season-2018.json') as GameData[];
      case 'season-2019.json': return require('./seasons/season-2019.json') as GameData[];
      case 'season-2020.json': return require('./seasons/season-2020.json') as GameData[];
      case 'season-2021.json': return require('./seasons/season-2021.json') as GameData[];
      case 'season-2022.json': return require('./seasons/season-2022.json') as GameData[];
      case 'season-2023.json': return require('./seasons/season-2023.json') as GameData[];
      case 'season-2024.json': return require('./seasons/season-2024.json') as GameData[];
      case 'season-2025.json': return require('./seasons/season-2025.json') as GameData[];
      default: return null;
    }
  } catch {
    // Environments without bundled JSON support (e.g. vite-node) land
    // here — callers fall back to the demo board.
    return null;
  }
}
