/**
 * Generate data/seasonFiles.ts — the static require() registry for every
 * season JSON bundle in data/seasons/.
 *
 * Metro can only bundle statically analyzable require() calls, so the
 * registry has to be spelled out file-by-file. This script derives it from
 * whatever season files exist on disk, keeping the registry in lockstep
 * with the converted data (it also runs automatically at the end of
 * scripts/convert-jeopardy-data.ts).
 *
 * Usage:
 *   npm run generate-registry
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const SEASONS_DIR = path.join(__dirname, '..', 'data', 'seasons');
const OUT_FILE = path.join(__dirname, '..', 'data', 'seasonFiles.ts');

export function generateSeasonRegistry(): void {
  const files = fs.readdirSync(SEASONS_DIR)
    .filter(f => /^season-\d+\.json$/.test(f))
    .sort();

  const cases = files
    .map(f => `      case '${f}': return require('./seasons/${f}') as GameData[];`)
    .join('\n');

  const content = `// AUTO-GENERATED by scripts/generate-season-registry.ts — do not edit.
// Regenerate with: npm run generate-registry
//
// Metro needs static require() calls to bundle the season JSON. The
// requires live inside a function body so each season is parsed lazily
// on first use (inline requires) — only the season being played is ever
// loaded into memory.
import type { GameData } from './gameLoader';

export function loadSeasonFile(file: string): GameData[] | null {
  try {
    switch (file) {
${cases}
      default: return null;
    }
  } catch {
    // Environments without bundled JSON support (e.g. vite-node) land
    // here — callers fall back to the demo board.
    return null;
  }
}
`;

  fs.writeFileSync(OUT_FILE, content);
  console.log(`Wrote data/seasonFiles.ts with ${files.length} season(s)`);
}

if (require.main === module) generateSeasonRegistry();
